{
 "title": "XRootD Read/Write/Mapc",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "XRootD MapC Lookup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "xrootd_exit{mode=\"xrdmapc\"}",
     "legendFormat": "{{hostname}} xrdmapc"
    }
   ]
  },
  {
   "title": "XRootD Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "xrootd_exit{mode=\"write\"}",
     "legendFormat": "{{hostname}} {{protocol}}"
    }
   ]
  },
  {
   "title": "XRootD Read Davs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "xrootd_exit{mode=\"read\", protocol=\"davs\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "XRootD Read https",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "xrootd_exit{mode=\"read\", protocol=\"https\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "XRootD Read root",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "xrootd_exit{mode=\"read\", protocol=\"root\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}